from __future__ import annotations
from typing import Protocol
from uuid import UUID
from ..domain.models import CanonicalEvent, EventRecord
from ..domain.queries import EventPage, EventQuery

class EventRepository(Protocol):
    def add(self, event: EventRecord) -> None: ...
    def get(self, event_uuid: UUID) -> EventRecord | None: ...
    def search(self, query: EventQuery) -> EventPage: ...

class CanonicalEventRepository(Protocol):
    def add(self, event: CanonicalEvent) -> None: ...
    def update(self, event: CanonicalEvent) -> None: ...
    def get(self, event_uuid: UUID) -> CanonicalEvent | None: ...
    def find_candidates(self, observation: EventRecord) -> tuple[CanonicalEvent, ...]: ...
